import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'setting': 'SETTINGS',
          'premium': 'Don’t miss out on exclusive features Tap to upgrade!',
          'language': 'Language',
          'yourPLan': 'Your Plan',
          'voice': 'Voice',
          'about': 'About',
          'rateUs': 'Rate Us',
          'shareWithF': 'Share with Friends',
          'terms': 'Terms of Use',
          'privacy': 'Privacy policy',
          'poweredBy': 'powered By',
          'history': 'HISTORY',
          'noData': 'Not data  found',
          'doYouDelete': 'Do to want to Delete ?',
          'areYouConfirm': 'Are you confirm',
          'confirm': 'Confirm',
          'cancel': 'Cancel',
          'restore': 'Restore',
          'premiumAdvanced':
          'Advanced: Full unlimited access for complex tasks and management.',
          'premiumSub1': 'Unlimited request (per day: ∞)',
          'premiumSub2': 'Advanced AI Model(Turbo)',
          'premiumSub3': 'AI remembers chat history',
          'premiumSub4': 'AI Art Generator (Per day: ∞)',
          'premiumSub5': 'Ads free experience',
          'month': 'Month',
          'week': 'Week',
          'perWeek': 'per week',
          'perMonth': 'per month',
          'perYear': 'per year',
          'daysFree': '3 DAYS FREE',
          'me': 'ME',
          'askNewQuestion': 'Ask new question',
          'copy': 'Copy',
          'historyEmpty': 'History Is Empty',
          'pleaseEnterText': 'Please Enter Text',
          'continueChat': 'Continue To Chat',
          'startTrail': 'Start Free Trial And Plan',
          'askSomething': 'Ask Something',
          'premiumPrice1': 'INR 183.88/week',
          'premiumPrice2': 'INR 399.00/week',
          'premiumPrice3': 'INR 95.87/week',
          'voiceIsOff': 'Voice Is Off',
          'offer1' : '1 Month',
          'offer2' : '1 Week',
          'offer3' : '1 Year',
          'imageGeneration' : 'Image Generation',
          'imageSize' : 'Image size',
          'imagePreview' : 'Image Preview',
          'share' : 'Share',
          'save' : 'Save',
          'dark' : 'Dark',
          'voiceIsOn' : 'Voice On',
          'year' : 'Year',
          'alreadyPremium' : 'Already You are Premium',
          'buyPremium' : 'Buy Premium',
        },
        'japa_JAPA': {
          'setting': '設定',
          'premium': '限定機能をお見逃しなくタップしてアップグレード！',
          'language': '言語',
          'yourPLan': 'あなたの計画',
          'voice': '声',
          'about': 'だいたい',
          'rateUs': '私たちを評価してください',
          'shareWithF': '友人たちと分ける',
          'terms': '利用規約',
          'privacy': 'プライバシーポリシー',
          'poweredBy': '搭載',
          'history': '歴史',
          'noData': 'データが見つかりません',
          'doYouDelete': '削除しますか?',
          'areYouConfirm': '確認しましたか',
          'confirm': '確認',
          'cancel': 'キャンセル',
          'restore': '戻す',
          'premiumAdvanced': '高度: 複雑なタスクと管理のための無制限の完全アクセス。',
          'premiumSub1': 'リクエスト無制限（1日あたり：∞）',
          'premiumSub2': '高度な AI モデル (ターボ)',
          'premiumSub3': 'AIがチャット履歴を記憶',
          'premiumSub4': 'AI アート ジェネレーター (1 日あたり: ∞)',
          'premiumSub5': '広告なしのエクスペリエンス',
          'month': '月',
          'week': 'Week週',
          'perWeek': '週ごと',
          'perMonth': '毎月',
          'perYear': '1年当たり',
          'daysFree': '3日間無料',
          'me': '自分',
          'askNewQuestion': '新しい質問をする',
          'copy': 'コピー',
          'historyEmpty': '履歴は空です',
          'pleaseEnterText': 'テキストを入力してください',
          'continueChat': 'チャットを続ける',
          'startTrail': '無料試用版を開始して計画する',
          'askSomething': '何かを求めます',
          'premiumPrice1': 'INR 183.88/週',
          'premiumPrice2': 'INR 399.00/週',
          'premiumPrice3': 'INR 95.87/月',
          'voiceIsOff': '音声がオフです',
          'offer1' : '1 月',
          'offer2' : '1 週',
          'offer3' : '12 月',
          'imageGeneration' : '画像生成',
          'imageSize' : '画像サイズ',
          'imagePreview' : '画像プレビュー',
          'share' : '共有',
          'save' : '保存',
          'dark' : '暗い',
          'voiceIsOn' : 'ボイスオン',
          'year' : '年',
          'alreadyPremium' : 'すでにあなたはプレミアムです',
          'buyPremium' : 'プレミアムを購入',
        },
        'turk_TURK': {
          'setting': 'AYARLAR',
          'premium':
              'ChatU yu 3 gün ücretsiz deneyin. Premium u etkinleştirmek için dokunun.',
          'language': 'Dil',
          'yourPLan': 'Senin planın',
          'voice': 'Ses',
          'about': 'Hakkında',
          'rateUs': 'Bizi değerlendirin',
          'shareWithF': 'Arkadaşlarınla ​​paylaş',
          'terms': 'Kullanım Şartları',
          'privacy': 'Gizlilik Politikası',
          'poweredBy': 'tarafından desteklenmektedir',
          'history': 'TARİH',
          'noData': 'veri bulunamadı',
          'doYouDelete': 'Silmek istiyor musunuz?',
          'areYouConfirm': 'onaylıyor musun',
          'confirm': 'Onaylamak',
          'cancel': 'İptal etmek',
          'restore': 'Eski haline getirmek',
          'premiumAdvanced': 'Gelişmiş: Karmaşık görevler ve yönetim için tam sınırsız erişim.',
          'premiumSub1': 'Sınırsız istek (günlük: ∞)',
          'premiumSub2': 'Gelişmiş AI Modeli(Turbo)',
          'premiumSub3': 'AI sohbet geçmişini hatırlar',
          'premiumSub4': 'AI Art Generator (Günlük: ∞)',
          'premiumSub5': 'Reklamsız deneyim',
          'month': 'Ay',
          'week': 'Hafta',
          'perWeek': 'haftada',
          'perMonth': 'her ay',
          'perYear': 'yıl başına',
          'daysFree': '3 GÜN ÜCRETSİZ',
          'me': 'BEN',
          'askNewQuestion': 'yeni soru sor',
          'copy': 'kopyala',
          'historyEmpty': 'Geçmiş Boş',
          'pleaseEnterText': 'Lütfen Metni Girin',
          'continueChat': 'Sohbete Devam Et',
          'startTrail': 'Ücretsiz denemeye başlayın ve planlayın',
          'askSomething': 'Bir şey sor',
          'premiumPrice1': 'INR 183.88/ay',
          'premiumPrice2': 'INR 399.00/hafta',
          'premiumPrice3': 'INR 95.87/ay',
          'voiceIsOff': 'Ses Kapalı',
          'offer1' : '1 ay',
          'offer2' : '1 Hafta',
          'offer3' : '12 ay',
          'imageGeneration' : 'Image Generation',
          'imageSize' : 'Görüntü boyutu',
          'imagePreview' : 'Resim Önizleme',
          'share' : 'Paylaşmak',
          'save' : 'Kaydetmek',
          'dark' : 'Karanlık',
          'voiceIsOn' : 'Ses Açık',
          'year' : 'Yıl',
          'alreadyPremium' : 'Zaten Premium\'sun',
          'buyPremium' : 'Premium Satın Al',
        },
        'polish_POLISH': {
          'setting': 'USTAWIENIA',
          'premium': 'Wypróbuj ChatU przez 3 dni za darmo. Dotknij, aby aktywować premium.',
          'language': 'Język',
          'yourPLan': 'Twój plan',
          'voice': 'Głos',
          'about': 'O',
          'rateUs': 'Oceń nas',
          'shareWithF': 'Podziel się z przyjaciółmi',
          'terms': 'Warunki korzystania',
          'privacy': 'Polityka prywatności',
          'poweredBy': 'zasilany przez',
          'history': 'HISTORIA',
          'noData': 'Nie znaleziono danych',
          'doYouDelete': 'Czy chcesz usunąć?',
          'areYouConfirm': 'Czy potwierdzasz',
          'confirm': 'Potwierdzać',
          'cancel': 'Anulować',
          'restore': 'Przywrócić',
          'premiumAdvanced': 'Zaawansowany: Pełny nieograniczony dostęp do złożonych zadań i zarządzania.',
          'premiumSub1': 'Nieograniczone żądanie (na dzień: ∞)',
          'premiumSub2': 'Zaawansowany model AI (Turbo)',
          'premiumSub3': 'AI zapamiętuje historię czatów',
          'premiumSub4': 'Generator grafiki AI (dziennie: ∞)',
          'premiumSub5': 'Bez reklam',
          'month': 'Miesiąc',
          'week': 'Tydzień',
          'perWeek': 'na tydzień',
          'perMonth': 'na miesiąc',
          'perYear': 'na rok',
          'daysFree': '3 DNI ZA DARMO',
          'me': 'JA',
          'askNewQuestion': 'Zadaj nowe pytanie',
          'copy': 'Kopiuj',
          'historyEmpty': 'Historia jest pusta',
          'pleaseEnterText': 'Wprowadź tekst',
          'continueChat': 'Kontynuuj czat',
          'startTrail': 'Rozpocznij bezpłatny okres próbny i planuj',
          'askSomething': 'Zapytać o coś',
          'premiumPrice1': 'INR 183.88/miesiąc',
          'premiumPrice2': 'INR 399.00/tydzień',
          'premiumPrice3': 'INR 95.87/miesiąc',
          'voiceIsOff': 'Głos jest wyłączony',
          'offer1' : '1 Miesiąc',
          'offer2' : '1 Tydzień',
          'offer3' : '12 Miesiąc',
          'imageGeneration' : 'Generowanie obrazu',
          'imageSize' : 'Rozmiar obrazu',
          'imagePreview' : 'Podgląd obrazu',
          'share' : 'Udział',
          'save' : 'Ratować',
          'dark' : 'Ciemny',
          'voiceIsOn' : 'Włącz głos',
          'year' : 'Rok',
          'alreadyPremium' : 'Już jesteś Premium',
          'buyPremium' : 'Kup Premium',
        },
        'ity_ITY': {
          'setting': 'IMPOSTAZIONI',
          'premium': 'Prova gratuitamente ChatU per 3 giorni. Tocca per attivare il servizio premium.',
          'language': 'Lingua',
          'yourPLan': 'Il tuo piano',
          'voice': 'Voce',
          'about': 'Di',
          'rateUs': 'Valutaci',
          'shareWithF': 'Condividere con gli amici',
          'terms': 'Termini di utilizzo',
          'privacy': 'Politica sulla riservatezza',
          'poweredBy': 'offerto da',
          'history': 'STORIA',
          'noData': 'Dati non trovati',
          'doYouDelete': 'Vuoi eliminare?',
          'areYouConfirm': 'Confermi',
          'confirm': 'Confermare',
          'cancel': 'Annulla',
          'restore': 'Ristabilire',
          'premiumAdvanced': 'Avanzato: accesso illimitato completo per attività e gestione complesse.',
          'premiumSub1': 'Richiesta illimitata (al giorno: ∞)',
          'premiumSub2': 'Modello AI avanzato (Turbo)',
          'premiumSub3': 'L' 'intelligenza artificiale ricorda la cronologia delle chat',
          'premiumSub4': 'Generatore artistico AI (al giorno: ∞)',
          'premiumSub5': 'Esperienza senza pubblicità',
          'month': 'Mese',
          'week': 'Settimana',
          'perWeek': 'per week',
          'perMonth': 'al mese',
          'perYear': 'per anno',
          'daysFree': '3 GIORNI GRATIS',
          'me': 'ME',
          'askNewQuestion': 'Fai una nuova domanda',
          'copy': 'copia',
          'historyEmpty': 'La storia è vuota',
          'pleaseEnterText': 'Inserisci il testo',
          'continueChat': 'Continua a chattare',
          'startTrail': 'Inizia la prova gratuita e pianifica',
          'askSomething': 'Chiedi qualcosa',
          'premiumPrice1': 'INR 183.88/mese',
          'premiumPrice2': 'INR 399.00/settimana',
          'premiumPrice3': 'INR 95.87/mese',
          'voiceIsOff': 'La voce è disattivata',
          'offer1' : '1 Mese',
          'offer2' : '1 Settimana',
          'offer3' : '12 Mese',
          'imageGeneration' : 'Generazione di immagini',
          'imageSize' : 'Dimensione dell''immagine',
          'imagePreview' : 'Anteprima dell''immagine',
          'share' : 'Condividere',
          'save' : 'Salva',
          'dark' : 'Buio',
          'voiceIsOn' : 'Voce attiva',
          'year' : 'Anno',
          'alreadyPremium' : 'Sei già Premium',
          'buyPremium' : 'Acquista Premio',
        },
        'dutch_DUTCH': {
          'setting': 'INSTELLINGEN',
          'premium': 'Probeer ChatU 3 dagen gratis. Tik om premium te activeren.',
          'language': 'Taal',
          'yourPLan': 'Jou plan',
          'voice': 'Stem',
          'about': 'Over',
          'rateUs': 'Beoordeel ons',
          'shareWithF': 'Delen met vrienden',
          'terms': 'Gebruiksvoorwaarden',
          'privacy': 'Privacybeleid',
          'poweredBy': 'aangedreven door',
          'history': 'GESCHIEDENIS',
          'noData': 'Geen gegevens gevonden',
          'doYouDelete': 'Wilt u verwijderen?',
          'areYouConfirm': 'Bevestigt u',
          'confirm': 'Bevestigen',
          'cancel': 'Annuleren',
          'restore': 'Herstellen',
          'premiumAdvanced': 'Geavanceerd: Volledige onbeperkte toegang voor complexe taken en beheer.',
          'premiumSub1': 'Onbeperkt aanvragen (per dag: ∞)',
          'premiumSub2': 'Geavanceerd AI-model (turbo)',
          'premiumSub3': 'AI onthoudt de chatgeschiedenis',
          'premiumSub4': 'AI Art Generator (per dag: ∞)',
          'premiumSub5': 'Advertenties gratis ervaring',
          'month': 'Maand',
          'week': 'Week',
          'perWeek': 'per week',
          'perMonth': 'per maand',
          'perYear': 'per jaar',
          'daysFree': '3 DAGEN GRATIS',
          'me': 'MIJ',
          'askNewQuestion': 'Stel een nieuwe vraag',
          'copy': 'Kopiëren',
          'historyEmpty': 'Geschiedenis is leeg',
          'pleaseEnterText': 'Voer alstublieft tekst in',
          'continueChat': 'Ga door met chatten',
          'startTrail': 'Start gratis proef en plan',
          'askSomething': 'Iets vragen',
          'premiumPrice1': 'INR 183.88/maand',
          'premiumPrice2': 'INR 399.00/week',
          'premiumPrice3': 'INR 95.87/maand',
          'voiceIsOff': 'Stem is uitgeschakeld',
          'offer1' : '1 Maand',
          'offer2' : '1 week',
          'offer3' : '12 Maand',
          'imageGeneration' : 'Beeld generatie',
          'imageSize' : 'Afbeeldingsgrootte',
          'imagePreview' : 'Image Preview',
          'share' : 'Deel',
          'save' : 'Redden',
          'dark' : 'Donker',
          'voiceIsOn' : 'Stem aan',
          'year' : 'Jaar',
          'alreadyPremium' : 'U bent al Premium',
          'buyPremium' : 'Premium kopen',
        },
        'indo_INDO': {
          'setting': 'PENGATURAN',
          'premium': 'Coba ChatU 3 hari gratis. Ketuk untuk mengaktifkan premium.',
          'language': 'Bahasa',
          'yourPLan': 'Rencanamu',
          'voice': 'Suara',
          'about': 'Tentang',
          'rateUs': 'Nilai Kami',
          'shareWithF': 'Bagikan dengan Teman',
          'terms': 'Syarat Penggunaan',
          'privacy': 'Kebijakan pribadi',
          'poweredBy': 'dipersembahkan oleh',
          'history': 'SEJARAH',
          'noData': 'Tidak ditemukan data',
          'doYouDelete': 'Apakah ingin Menghapus ?',
          'areYouConfirm': 'Apakah Anda mengkonfirmasi',
          'confirm': 'Mengonfirmasi',
          'cancel': 'Membatalkan',
          'restore': 'Memulihkan',
          'premiumAdvanced': 'Lanjutan: Akses penuh tanpa batas untuk tugas dan manajemen yang rumit.',
          'premiumSub1': 'Permintaan tidak terbatas (per hari: ∞)',
          'premiumSub2': 'Model AI Tingkat Lanjut (Turbo)',
          'premiumSub3': 'AI mengingat riwayat obrolan',
          'premiumSub4': 'AI Art Generator (Per hari: ∞)',
          'premiumSub5': 'Pengalaman bebas iklan',
          'month': 'Bulan',
          'week': 'Pekan',
          'perWeek': 'per minggu',
          'perMonth': 'per bulan',
          'perYear': 'per tahun',
          'daysFree': '3 HARI GRATIS',
          'me': 'AKU',
          'askNewQuestion': 'Ajukan pertanyaan baru',
          'copy': 'Menyalin',
          'historyEmpty': 'Sejarah Kosong',
          'pleaseEnterText': 'Harap Masukkan Teks',
          'continueChat': 'Lanjutkan ke Obrolan',
          'startTrail': 'Mulai uji coba gratis dan rencanakan',
          'askSomething': 'Bertanya sesuatu',
          'premiumPrice1': 'INR 183.88/bulan',
          'premiumPrice2': 'INR 399.00/pekan',
          'premiumPrice3': 'INR 95.87/bulan',
          'voiceIsOff': 'Suara Mati',
          'offer1' : '1 Bulan',
          'offer2' : '1 Pekan',
          'offer3' : '12 Bulan',
          'imageGeneration' : 'Generasi Gambar',
          'imageSize' : 'Ukuran gambar',
          'imagePreview' : 'Pratinjau Gambar',
          'share' : 'Membagikan',
          'save' : 'Menyimpan',
          'dark' : 'Gelap',
          'voiceIsOn' : 'Suara Aktif',
          'year' : 'Tahun',
          'alreadyPremium' : 'Sudah Anda Premium',
          'buyPremium' : 'Beli Premium',
        },
        'por_PORTU': {
          'setting': 'CONFIGURAÇÕES',
          'premium': 'Experimente o ChatU por 3 dias grátis. Toque para ativar o Premium.',
          'language': 'Linguagem',
          'yourPLan': 'Seu plano',
          'voice': 'Voz',
          'about': 'Sobre',
          'rateUs': 'Nos avalie',
          'shareWithF': 'Compartilhe com amigos',
          'terms': 'Termos de uso',
          'privacy': 'Política de Privacidade',
          'poweredBy': 'distribuído por',
          'history': 'HISTÓRIA',
          'noData': 'Dados não encontrados',
          'doYouDelete': 'Quer Excluir?',
          'areYouConfirm': 'você confirma',
          'confirm': 'confirme',
          'cancel': 'Cancelar',
          'restore': 'Restaurar',
          'premiumAdvanced': 'Avançado: Acesso total e ilimitado para gerenciamento e tarefas complexas.',
          'premiumSub1': 'Solicitação ilimitada (por dia: ∞)',
          'premiumSub2': 'Modelo AI avançado (Turbo)',
          'premiumSub3': 'AI lembra o histórico de bate-papo',
          'premiumSub4': 'AI Art Generator (por dia: ∞)',
          'premiumSub5': 'Experiência gratuita de anúncios',
          'month': 'Mês',
          'week': 'Semana',
          'perWeek': 'por semana',
          'perMonth': 'por mês',
          'perYear': 'por ano',
          'daysFree': '3 DIAS GRÁTIS',
          'me': 'MEU',
          'askNewQuestion': 'Faça nova pergunta',
          'copy': 'cópia de',
          'historyEmpty': 'A história está vazia',
          'pleaseEnterText': 'Digite o texto',
          'continueChat': 'Continuar no bate-papo',
          'startTrail': 'Iniciar avaliação gratuita e planejar',
          'askSomething': 'Pergunta algo',
          'premiumPrice1': 'INR 183.88/mês',
          'premiumPrice2': 'INR 399.00/semana',
          'premiumPrice3': 'INR 95.87/mês',
          'voiceIsOff': 'Voz está desligada',
          'offer1' : '1 Mês',
          'offer2' : '1 Semana',
          'offer3' : '12 Mês',
          'imageGeneration' : 'Geração de imagem',
          'imageSize' : 'Tamanho da imagem',
          'imagePreview' : 'Pré-visualização de imagem',
          'share' : 'Compartilhar',
          'save' : 'Salvar',
          'dark' : 'Escuro',
          'voiceIsOn' : 'Voz Ligada',
          'year' : 'Ano',
          'alreadyPremium' : 'Já é Premium',
          'buyPremium' : 'Comprar Premium',
        },
        'ar_AR': {
          'setting': 'إعدادات',
          'premium': 'جرب ChatU 3 أيام مجانًا ، اضغط لتفعيل الإصدار المميز.',
          'language': 'لغة',
          'yourPLan': 'خطتك',
          'voice': 'صوت',
          'about': 'عن',
          'rateUs': 'قيمنا',
          'shareWithF': 'شارك مع الاصدقاء',
          'terms': 'شروط الاستخدام',
          'privacy': 'سياسة الخصوصية',
          'poweredBy': 'مشغل بواسطة',
          'history': 'تاريخ',
          'noData': 'لم يتم العثور على البيانات',
          'doYouDelete': 'هل تريد حذف؟',
          'areYouConfirm': 'هل انت تؤكد',
          'confirm': 'يتأكد',
          'cancel': 'يلغي',
          'restore': 'يعيد',
          'premiumAdvanced': 'متقدم: الوصول الكامل غير المحدود للمهام المعقدة والإدارة.',
          'premiumSub1': 'طلب غير محدود (في اليوم: ∞)',
          'premiumSub2': 'نموذج ذكاء اصطناعي متقدم (توربو)',
          'premiumSub3': 'يتذكر الذكاء الاصطناعي محفوظات الدردشة',
          'premiumSub4': 'مولد الفن بالذكاء الاصطناعي (في اليوم: ∞)',
          'premiumSub5': 'تجربة خالية من الإعلانات',
          'month': 'شهر',
          'week': 'أسبوع',
          'perWeek': 'في الاسبوع',
          'perMonth': 'كل شهر',
          'perYear': 'كل سنة',
          'daysFree': '3 أيام مجانية',
          'me': 'أنا',
          'askNewQuestion': 'اطرح سؤالا جديدا',
          'copy': 'ينسخ',
          'historyEmpty': 'التاريخ فارغ',
          'pleaseEnterText': 'الرجاء إدخال نص',
          'continueChat': 'استمر في الدردشة',
          'startTrail': 'ابدأ الإصدار التجريبي المجاني وخطط',
          'askSomething': 'اسأل شيئا',
          'premiumPrice1': 'INR 183.88/شهر',
          'premiumPrice2': 'INR 399.00/أسبوع',
          'premiumPrice3': 'INR 95.87/شهر',
          'voiceIsOff': 'الصوت مغلق',
          'offer1' : '1 شهر',
          'offer2' : '1 أسبوع',
          'offer3' : '12 شهر',
          'imageGeneration' : 'توليد الصور',
          'imageSize' : 'حجم الصورة',
          'imagePreview' : 'معاينة الصورة',
          'share' : 'يشارك',
          'save' : 'يحفظ',
          'dark' : 'مظلم',
          'voiceIsOn' : 'صوت على',
          'year' : 'سنة',
          'alreadyPremium' : 'بالفعل أنت بريميوم',
          'buyPremium' : 'شراء قسط',
        },
        'hi_IN': {
          'setting': 'समायोजन',
          'premium': 'ChatU को 3 दिन नि:शुल्क आज़माएं। प्रीमियम सक्रिय करने के लिए टैप करें।',
          'language': 'भाषा',
          'yourPLan': 'तुम्हारी योजना',
          'voice': 'आवाज़',
          'about': 'के बारे में',
          'rateUs': 'हमें रेटिंग दें',
          'shareWithF': 'दोस्तों के साथ बांटें',
          'terms': 'उपयोग की शर्तें',
          'privacy': 'गोपनीयता नीति',
          'poweredBy': 'द्वारा संचालित',
          'history': 'इतिहास',
          'noData': 'डेटा नहीं मिला',
          'doYouDelete': 'हटाना चाहते हैं?',
          'areYouConfirm': 'क्या आप कन्फर्म हैं',
          'confirm': 'पुष्टि करना',
          'cancel': 'रद्द करना',
          'restore': 'पुनर्स्थापित करना',
          'premiumAdvanced':
          'उन्नत: जटिल कार्यों और प्रबंधन के लिए पूर्ण असीमित पहुंच।',
          'premiumSub1': 'असीमित अनुरोध (प्रति दिन: ∞)',
          'premiumSub2': 'उन्नत एआई मॉडल (टर्बो)',
          'premiumSub3': 'एआई को चैट हिस्ट्री याद है',
          'premiumSub4': 'एआई आर्ट जेनरेटर (प्रति दिन: ∞)',
          'premiumSub5': 'विज्ञापन मुक्त अनुभव',
          'month': 'महीना',
          'week': 'सप्ताह',
          'perWeek': 'प्रति सप्ताह',
          'perMonth': 'प्रति महीने',
          'perYear': 'प्रति वर्ष',
          'daysFree': '3 दिन मुफ़्त',
          'me': 'मुझे',
          'askNewQuestion': 'नया प्रश्न पूछें',
          'copy': 'प्रतिलिपि',
          'historyEmpty': 'इतिहास खाली है',
          'pleaseEnterText': 'कृपया पाठ दर्ज करें',
          'continueChat': 'चैट करना जारी रखें',
          'startTrail': 'नि:शुल्क परीक्षण शुरू करें और योजना बनाएं',
          'askSomething': 'कुछ पूछें',
          'premiumPrice1': 'INR 183.88/महीना',
          'premiumPrice2': 'INR 399.00/सप्ताह',
          'premiumPrice3': 'INR 95.87/महीना',
          'voiceIsOff': 'आवाज बंद है',
          'offer1' : '1 महीना',
          'offer2' : '1 सप्ताह',
          'offer3' : '12 महीना',
          'imageGeneration' : 'छवि निर्माण',
          'imageSize' : 'छवि का आकार',
          'imagePreview' : 'छवि पूर्वावलोकन',
          'share' : 'शेयर करना',
          'save' : 'बचाना',
          'dark' : 'अँधेरा',
          'voiceIsOn' : 'वॉयस ऑन',
          'year' : 'वर्ष',
          'alreadyPremium' : 'आप पहले से ही प्रीमियम हैं',
          'buyPremium' : 'प्रीमियम खरीदें',
        },
        'russ_RUSS': {
          'setting': 'НАСТРОЙКИ',
          'premium':
              'Попробуйте ChatU 3 дня бесплатно. Нажмите, чтобы активировать премиум.',
          'language': 'Язык',
          'yourPLan': 'Ваш план',
          'voice': 'Голос',
          'about': 'О',
          'rateUs': 'Оцените нас',
          'shareWithF': 'Поделиться с друзьями',
          'terms': 'Условия эксплуатации',
          'privacy': 'Политика конфиденциальности',
          'poweredBy': 'питаться от',
          'history': 'ИСТОРИЯ',
          'noData': 'Данные не найдены',
          'doYouDelete': 'Сделать, чтобы удалить?',
          'areYouConfirm': 'Вы подтверждаете',
          'confirm': 'Подтверждать',
          'cancel': 'Отмена',
          'restore': 'Восстановить',
          'premiumAdvanced':
              'Расширенный: полный неограниченный доступ для сложных задач и управления.',
          'premiumSub1': 'Неограниченный запрос (в день: ∞)',
          'premiumSub2': 'Усовершенствованная модель ИИ (турбо)',
          'premiumSub3': 'ИИ запоминает историю чата',
          'premiumSub4': 'AI Art Generator (в день: ∞)',
          'premiumSub5': 'Без рекламы',
          'month': 'Месяц',
          'week': 'Неделя',
          'perWeek': 'в неделю',
          'perMonth': 'в месяц',
          'perYear': 'в год',
          'daysFree': '3 ДНЯ БЕСПЛАТНО',
          'me': 'МНЕ',
          'askNewQuestion': 'Задать новый вопрос',
          'copy': 'Копировать',
          'historyEmpty': 'История пуста',
          'pleaseEnterText': 'Пожалуйста, введите текст',
          'continueChat': 'Продолжить общение',
          'startTrail': 'Начать бесплатную пробную версию и планировать',
          'askSomething': 'Спроси что-нибудь',
          'premiumPrice1': 'INR 183.88/mes',
          'premiumPrice2': 'INR 399.00/неделя',
          'premiumPrice3': 'INR 95.87/mes',
          'voiceIsOff': 'Голос выключен',
          'offer1' : '1 Mes',
          'offer2' : '1 Semana',
          'offer3' : '12 Mes',
          'imageGeneration' : 'Генерация изображения',
          'imageSize' : 'Размер изображения',
          'imagePreview' : 'Предварительный просмотр изображения',
          'share' : 'Делиться',
          'save' : 'Сохранять',
          'dark' : 'Темный',
          'voiceIsOn' : 'Голос включен',
          'year' : 'Год',
          'alreadyPremium' : 'Вы уже Премиум',
          'buyPremium' : 'Купить Премиум',
        },
        'ch_CH': {
          'setting': '設置',
          'premium': '免費試用 ChatU 3 天。點擊以激活高級版。',
          'language': '語言',
          'yourPLan': '你的計劃',
          'voice': '嗓音',
          'about': '關於',
          'rateUs': '評價我們',
          'shareWithF': '和朋友分享',
          'terms': '使用條款',
          'privacy': '隱私政策',
          'poweredBy': '供電',
          'history': '歷史',
          'noData': '未找到數據',
          'doYouDelete': '做要刪除嗎？',
          'areYouConfirm': '你確認嗎',
          'confirm': '確認',
          'cancel': '取消',
          'restore': '恢復',
          'premiumAdvanced': '高級：完全無限制地訪問複雜的任務和管理。',
          'premiumSub1': '無限請求（每天：∞）',
          'premiumSub2': '高級人工智能模型（Turbo）',
          'premiumSub3': 'AI 記住聊天記錄',
          'premiumSub4': '人工智能藝術生成器（每天：∞）',
          'premiumSub5': '無廣告體驗',
          'month': '月',
          'week': '星期',
          'perWeek': '每個星期',
          'perMonth': '每月',
          'perYear': '每年',
          'daysFree': '3 天免費',
          'me': '我',
          'askNewQuestion': '問新問題',
          'copy': '複製',
          'historyEmpty': '歷史是空的',
          'pleaseEnterText': '請輸入文字',
          'continueChat': '繼續聊天',
          'startTrail': '開始免費試用和計劃',
          'askSomething': '問點事',
          'premiumPrice1': 'INR 183.88/月',
          'premiumPrice2': 'INR 399.00/星期',
          'premiumPrice3': 'INR 95.87/月',
          'voiceIsOff': '语音关闭',
          'offer1' : '1 月',
          'offer2' : '1 星期',
          'offer3' : '12 月',
          'imageGeneration' : '图像生成',
          'imageSize' : '图片大小',
          'imagePreview' : '图片预览',
          'share' : '分享',
          'save' : '节省',
          'dark' : '黑暗的',
          'voiceIsOn' : '语音开启',
          'year' : '年',
          'alreadyPremium' : '你已经是高级会员了',
          'buyPremium' : '购买高级版',
        },
        'gem_GEM': {
          'setting': 'EINSTELLUNGEN',
          'premium':
              'Testen Sie ChatU 3 Tage kostenlos. Tippen Sie, um Premium zu aktivieren.',
          'language': 'Sprache',
          'yourPLan': 'Your PlanDein Plan',
          'voice': 'Stimme',
          'about': 'Um',
          'rateUs': 'Bewerten Sie uns',
          'shareWithF': 'Mit Freunden teilen',
          'terms': 'Nutzungsbedingungen',
          'privacy': 'Datenschutz-Bestimmungen',
          'poweredBy': 'bereitgestellt von',
          'history': 'GESCHICHTE',
          'noData': 'Keine Daten gefunden',
          'doYouDelete': 'Möchten Sie löschen?',
          'areYouConfirm': 'Bestätigen Sie',
          'confirm': 'Bestätigen',
          'cancel': 'Stornieren',
          'restore': 'Wiederherstellen',
          'premiumAdvanced':
              'Erweitert: Uneingeschränkter Vollzugriff für komplexe Aufgaben und Verwaltung.',
          'premiumSub1': 'Unbegrenzte Anfrage (pro Tag: ∞)',
          'premiumSub2': 'Erweitertes KI-Modell (Turbo)',
          'premiumSub3': 'AI merkt sich den Chat-Verlauf',
          'premiumSub4': 'AI Art Generator (pro Tag: ∞)',
          'premiumSub5': 'Werbefreies Erlebnis',
          'month': 'Monat',
          'week': 'Woche',
          'perWeek': 'pro Woche',
          'perMonth': 'pro Monat',
          'perYear': 'pro Jahr',
          'daysFree': '3 TAGE KOSTENLOS',
          'me': 'MEMICH',
          'askNewQuestion': 'Neue Frage stellen',
          'copy': 'Kopieren',
          'historyEmpty': 'Die Geschichte ist leer',
          'pleaseEnterText': 'Bitte Text eingeben',
          'continueChat': 'Weiter zum Chatten',
          'startTrail': 'Kostenlose Testversion starten und planen',
          'askSomething': 'Etwas fragen',
          'premiumPrice1': 'INR 183.88/Monat',
          'premiumPrice2': 'INR 399.00/Woche',
          'premiumPrice3': 'INR 95.87/Monat',
          'voiceIsOff': 'Stimme ist aus',
          'offer1' : '1 Monat',
          'offer2' : '1 Woche',
          'offer3' : '12 Monat',
          'imageGeneration' : 'Bilderzeugung',
          'imageSize' : 'Bildgröße',
            'imagePreview' : 'Bildvorschau',
          'share' : 'Aktie',
          'save' : 'Speichern',
          'dark' : 'Dunkel',
          'voiceIsOn' : 'Stimme an',
          'year' : 'Jahr',
          'alreadyPremium' : 'Sie sind bereits Premium',
          'buyPremium' : 'Prämie kaufen',
        },
        'fre_FRE': {
          'setting': 'PARAMÈTRES',
          'premium':
              'Essayez ChatU 3 jours gratuitement.Appuyez pour activer la prime.',
          'language': 'Langue',
          'yourPLan': 'Votre plan',
          'voice': 'Voix',
          'about': 'À propos',
          'rateUs': 'Évaluez nous',
          'shareWithF': 'Partager avec des amis',
          'terms': 'Conditions d' 'utilisation',
          'privacy': 'Politique de confidentialité',
          'poweredBy': 'alimenté par',
          'history': 'HISTOIRE',
          'noData': 'Pas de données trouvées',
          'doYouDelete': 'Voulez-vous supprimer?',
          'areYouConfirm': 'Confirmez-vous',
          'confirm': 'Confirmer',
          'cancel': 'Annuler',
          'restore': 'Restaurer',
          'premiumAdvanced': 'Avancé : accès illimité complet pour les tâches et la gestion complexes.',
          'premiumSub1': 'Requête illimitée (par jour : ∞)',
          'premiumSub2': 'Modèle d' 'IA avancé (Turbo)',
          'premiumSub3': 'L' 'IA se souvient de l' 'historique des discussions',
          'premiumSub4': 'Générateur d' 'art IA (par jour : ∞)',
          'premiumSub5': 'Expérience sans publicité',
          'month': 'Mois',
          'week': 'Semaine',
          'perWeek': 'par semaine',
          'perMonth': 'par mois',
          'perYear': 'par an',
          'daysFree': '3 JOURS GRATUITS',
          'me': 'MOI',
          'askNewQuestion': 'Poser une nouvelle question',
          'copy': 'Copie',
          'historyEmpty': 'L' 'historique est vide',
          'pleaseEnterText': 'Veuillez entrer du texte',
          'continueChat': 'Continuer à discuter',
          'startTrail': 'Commencez l' 'essai gratuit et planifiez',
          'askSomething': 'Demander quelque chose',
          'premiumPrice1': 'INR 183.88/mois',
          'premiumPrice2': 'INR 399.00/semaine',
          'premiumPrice3': 'INR 95.87/mois',
          'voiceIsOff': 'La voix est désactivée',
          'offer1' : '1 Mois',
          'offer2' : '1 Semaine',
          'offer3' : '12 Mois',
          'imageGeneration' : 'Génération d images',
          'imageSize' : 'Taille de l image',
          'imagePreview' : 'Aperçu de l image',
          'share' : 'Partager',
          'save' : 'Sauvegarder',
          'dark' : 'Sombre',
          'voiceIsOn' : 'Voix activée',
          'year' : 'Année',
          'alreadyPremium' : 'Vous êtes déjà Premium',
          'buyPremium' : 'Acheter Premium',
        },
        'sp_SP': {
          'setting': 'AJUSTES',
          'premium': 'Prueba ChatU 3 días gratis. Toca para activar premium.',
          'language': 'Idioma',
          'yourPLan': 'Tu plan',
          'voice': 'Voz',
          'about': 'About',
          'rateUs': 'Acerca de',
          'shareWithF': 'Compartir con amigos',
          'terms': 'Condiciones de uso',
          'privacy': 'Política de privacidad',
          'poweredBy': 'energizado por',
          'history': 'HISTORIA',
          'noData': 'No se encontraron datos',
          'doYouDelete': '¿Quieres eliminar?',
          'areYouConfirm': '¿Estás confirmando',
          'confirm': 'Confirmar',
          'cancel': 'Cancelar',
          'restore': 'Restaurar',
          'premiumAdvanced': 'Avanzado: acceso completo e ilimitado para tareas y gestión complejas.',
          'premiumSub1': 'Solicitud ilimitada (por día: ∞)',
          'premiumSub2': 'Modelo AI avanzado (Turbo)',
          'premiumSub3': 'AI recuerda el historial de chat',
          'premiumSub4': 'Generador de arte AI (Por día: ∞)',
          'premiumSub5': 'Experiencia sin anuncios',
          'month': 'Mes',
          'week': 'Semana',
          'perWeek': 'por semana',
          'perMonth': 'por mes',
          'perYear': 'por año',
          'daysFree': '3 DÍAS GRATIS',
          'me': 'A MÍ',
          'askNewQuestion': 'Haz una nueva pregunta',
          'copy': 'Copiar',
          'historyEmpty': 'La historia está vacía',
          'pleaseEnterText': 'Por favor ingrese texto',
          'continueChat': 'Continuar al chat',
          'startTrail': 'Comience la prueba gratuita y planifique',
          'askSomething': 'Pregunta algo',
          'premiumPrice1': 'INR 183.88/mes',
          'premiumPrice2': 'INR 399.00/semana',
          'premiumPrice3': 'INR 95.87/mes',
          'voiceIsOff': 'La voz está apagada',
          'offer1' : '1 Mes',
          'offer2' : '1 Semana',
          'offer3' : '12 Mes',
          'imageGeneration' : 'Generación de imágenes',
          'imageSize' : 'Tamaño de la imagen',
          'imagePreview' : 'Vista previa de la imagen',
          'share' : 'Compartir',
          'save' : 'Ahorrar',
          'dark' : 'Oscuro',
          'voiceIsOn' : 'Voz activada',
          'year' : 'Año',
          'alreadyPremium' : 'Ya eres Premium',
          'buyPremium' : 'Comprar Premium',
        }
      };
}
